version: '3.8'
services:
    db:
      image: postgres:13
      container_name: JSB-postgres
      restart: always
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123456
      volumes:
        - JSB-postgres:/var/lib/postgresql/data

volumes:
  JSB-postgres:
    name: JSB-postgres